version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
